/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PsnTrophies;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue Gavidia
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    PSNUsers psn;
    Trophy type;
    public Main() {
        psn = new PSNUsers();
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        addTroph = new javax.swing.JButton();
        AddUser = new javax.swing.JButton();
        Deactivate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextArea();
        busqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AddTrophy = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        game = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ContinuarAddTrophy = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setPreferredSize(new java.awt.Dimension(847, 621));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTroph.setText("Add Trophy");
        addTroph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrophActionPerformed(evt);
            }
        });
        background.add(addTroph, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 100, 60));

        AddUser.setText("Add user");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });
        background.add(AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 100, 60));

        Deactivate.setText("Deactivate");
        background.add(Deactivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 100, 60));

        Console.setColumns(20);
        Console.setRows(5);
        jScrollPane1.setViewportView(Console);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 590, 450));
        background.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 100, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 521));

        AddTrophy.setBackground(new java.awt.Color(204, 204, 204));
        AddTrophy.setPreferredSize(new java.awt.Dimension(847, 621));
        AddTrophy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Titulo");
        AddTrophy.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        AddTrophy.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 220, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Datos del trofeo");
        AddTrophy.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));
        AddTrophy.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 220, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Juego");
        AddTrophy.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));
        AddTrophy.add(game, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 220, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TIPO");
        AddTrophy.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));
        AddTrophy.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 220, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usuario");
        AddTrophy.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        ContinuarAddTrophy.setText("Continuar");
        ContinuarAddTrophy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarAddTrophyActionPerformed(evt);
            }
        });
        AddTrophy.add(ContinuarAddTrophy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 120, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Usuario");
        AddTrophy.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jToggleButton1.setText("BRONCE");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        AddTrophy.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jToggleButton2.setText("PLATINO");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        AddTrophy.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jToggleButton3.setText("ORO");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        AddTrophy.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jToggleButton4.setText("PLATA");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        AddTrophy.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        getContentPane().add(AddTrophy, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        try {
            String user= JOptionPane.showInputDialog(this, "Ingrese el usuario a añadir");
            psn.addUser(user);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_AddUserActionPerformed

    private void addTrophActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrophActionPerformed
      
       background.setVisible(false);
       AddTrophy.setVisible(true);
       
        
    }//GEN-LAST:event_addTrophActionPerformed

    private void ContinuarAddTrophyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarAddTrophyActionPerformed
        try {
            String user = us.getText();
            String trophyGame = game.getText();
            String trophyName = title.getText();
            
            
            
            
            
            
            psn.addTrophieTo(user, trophyGame, trophyName,type );
        } catch (IOException ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_ContinuarAddTrophyActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        type = type.BRONCE;
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
          type = type.PLATINO;
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
           type = type.ORO;
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
           type = type.PLATA;
           
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void print(){
         System.out.println(" FECHA:   TIPO:  JUEGO:  DESCRIPCIÓN: ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTrophy;
    private javax.swing.JButton AddUser;
    private javax.swing.JTextArea Console;
    private javax.swing.JButton ContinuarAddTrophy;
    private javax.swing.JButton Deactivate;
    private javax.swing.JButton addTroph;
    private javax.swing.JPanel background;
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField game;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextField title;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
